<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_preprocess_node__article().
 */
function beargoyles_preprocess_node__article(array &$variables): void {
  $date = $variables['node']->getCreatedTime();

  $variables['date'] = \Drupal::service('date.formatter')
    ->format($date, 'dorquenet_medium');
}

/**
 * Implements hook_form_comment_form_alter().
 */
function beargoyles_form_comment_form_alter(
  array &$form,
  FormStateInterface $form_state,
): void {
  $form['actions']['submit']['#value'] = t('Post');

  $form['comment_body']['widget'][0]['value']['#title'] =
    t('Leave a comment');

  $form['comment_body']['widget'][0]['value']['#attributes']['class'][] =
    'beargoyles-comment-textarea';
}

/**
 * Implements hook_preprocess_comment().
 */
function beargoyles_preprocess_comment(array &$variables): void {
  $variables['posted_ago'] = \Drupal::service('date.formatter')
    ->formatTimeDiffSince(
      $variables['comment']->getCreatedTime(),
      ['granularity' => 1],
    );
}